version: '3'

services:
    web_app:
        build: .
        container_name: web_app
        working_dir: /app
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        environment:
            - PYTHONBUFFERED=1
        command: >
            bash -c " 
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"





